```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#' @import purrr
#' @import stats
#' @importFrom magrittr %>%
#' @details
#' Linear Regression with Little Bag of Bootstraps
"_PACKAGE"

#' @export
blblm <- function(formula, data, m = 10, B = 5000) {
  data_list <- split_data(data, m)
  estimates <- map(
    data_list,
    ~ lm_each_subsample(formula = formula, data = ., n = nrow(data), B = B)
  )
  res <- list(estimates = estimates, formula = formula)
  class(res) <- "blblm"
  invisible(res)
}


#' split data into m parts of approximated equal sizes
split_data <- function(data, m) {
  idx <- sample.int(m, nrow(data), replace = TRUE)
  data %>% split(idx)
}


#' compute the estimates
lm_each_subsample <- function(formula, data, n, B) {
  replicate(B, lm_each_boot(formula, data, n), simplify = FALSE)
}


#' compute the regression estimates for a blb dataset
lm_each_boot <- function(formula, data, n) {
  freqs <- rmultinom(1, n, rep(1, nrow(data)))
  lm1(formula, data, freqs)
}


#' estimate the regression estimates based on given number of repetitions
lm1 <- function(formula, data, freqs) {
  # drop the original closure of formula,
  # otherwise the formula will pick wrong variables from a parent scope.
  environment(formula) <- environment()
  fit <- lm(formula, data, weights = freqs)
  list(coef = blbcoef(fit), sigma = blbsigma(fit))
}


#' compute the coefficients from fit
blbcoef <- function(fit) {
  # YOUR CODE to compute the coefficients
  fit$coefficients
}


#' compute sigma from fit
blbsigma <- function(fit) {
  p <- fit$rank
  y <- model.extract(fit$model, "response") # response is not defined
  e <- fitted(fit) - y
  w <- fit$weights
  # YOUR CODE to compute sigma
  
}


#' @export
#' @method print blblm
print.blblm <- function(x, ...) {
  cat("blblm model")
}

# objest is blblm function output (the first function)
#' @export
#' @method sigma blblm
sigma.blblm <- function(object, confidence = FALSE, level = 0.95, ...) {
  est <- object$estimates
  # YOUR CODE to compute sigma and its c.i.
  # calcualte sigma with estimate without the fit
  # estimates have coef and sigma
  # est["sigma"] is a list of 10 subsamples, each is a list of 5000 bootstraps
  sigma = est["sigma"] %>%
    map(map(mean...))
  
  # have 10 sigma, then CI with quantile
}

#' @export
#' @method coef blblm
coef.blblm <- function(object, ...) {
  est <- object$estimates
  # YOUR CODE to compute the coefficients.
  est["coef"]
}


#' @export
#' @method confint blblm
confint.blblm <- function(object, parm = NULL, level = 0.95, ...) {
  if (is.null(parm)) {
    parm <- attr(terms(fit$formula), "term.labels")
  }
  # YOUR CODE to compute the confidence intervals
  # lookout for several coefficient so need to do rsum,rowmean, some sort of a matrix
}

#' @export
#' @method predict blblm
predict.blblm <- function(object, newdata, confidence = FALSE, level = 0.95, ...) {
  est <- object$estimates
  X <- model.matrix(reformulate(attr(terms(object$formula), "term.labels")), newdata)
  if (confidence) {
    # YOUR CODE to compute the predictions and their confidence intervals
  } else {
    # YOUR CODE to compute the predictions
  }
}
```


