---
title: "tele data"
output: html_document
---

```{r}
library("readxl") # read_excel
```

```{r}
telcom = read_excel('tele_data_original.xlsx', sheet = 1, col_names = TRUE, col_types = NULL, skip = 0)
```

```{r}
# identify and treat NA

# unique(telcom$C3H17M)

telcom$OVERTIME = ifelse(str_detect(telcom$OVERTIME, "-1"), sub('-1', NA, telcom$OVERTIME), telcom$OVERTIME)
telcom$OVERTIME = as.numeric(as.character(telcom$OVERTIME))
# sum(is.na(telcom$OVERTIME))

telcom$TECHCONS = ifelse(str_detect(telcom$TECHCONS, "-1"), sub('-1', NA, telcom$TECHCONS), telcom$TECHCONS)
telcom$TECHCONS = as.numeric(as.character(telcom$TECHCONS))
# sum(is.na(telcom$TECHCONS))

telcom$COMMTIME = ifelse(str_detect(telcom$COMMTIME, '-99999'), sub('-99999', NA, telcom$COMMTIME), telcom$COMMTIME)
telcom$COMMTIME = ifelse(str_detect(telcom$COMMTIME, '-0.1'), sub('-0.1', NA, telcom$COMMTIME), telcom$COMMTIME)
telcom$COMMTIME = as.numeric(as.character(telcom$COMMTIME))
# sum(is.na(telcom$COMMTIME))

telcom$SELFDRIV = ifelse(str_detect(telcom$SELFDRIV, '-1'), sub('-1', NA, telcom$SELFDRIV), telcom$SELFDRIV)
telcom$SELFDRIV = as.numeric(as.character(telcom$SELFDRIV))
# sum(is.na(telcom$SELFDRIV))

telcom$VEHPERWK = ifelse(str_detect(telcom$VEHPERWK, '-1'), sub('-1', NA, telcom$VEHPERWK), telcom$VEHPERWK)
telcom$VEHPERWK = as.numeric(as.character(telcom$VEHPERWK))
# sum(is.na(telcom$VEHPERWK))

telcom = na.omit(telcom)
```

```{r}
write.csv(telcom, "tele_data_clean.csv")
```

```{r}
glmfit = glm(C3H17M ~ OVERTIME + EFACT9 + EFACT6 + MANCONST + JOBCONST
                 + TECHCONS + CSO9FT2, 
                 family = binomial(link= "logit"), data = telcom)
```
